services:
  xcube:
    image: xcube:v1.0.0
    restart: always
    networks:
      - web
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 30s
        failure_action: rollback
        monitor: 10s
        max_failure_ratio: 0.1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.xcube-express.rule=Host(`xcube.connoisseur-suite.co.uk`)"
        - "traefik.http.routers.xcube-express.entrypoints=websecure"
        - "traefik.http.routers.xcube-express.tls=true"
        - "traefik.http.routers.xcube-express.tls.certresolver=production"
        - "traefik.http.services.xcube-express.loadbalancer.server.port=80"
networks:
  web:
    external: true