apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: databases
type: Opaque
stringData:
  MARIADB_ROOT_PASSWORD: "R0x70T9eZe0VnO6HcxEps9GlqG1jBvsL9U0mqWN9"
  MARIADB_PASSWORD: "R0x70T9eZe0VnO6HcxEps9GlqG1jBvsL9U0mqWN9"
