# kubectl apply -f databases/redis/do/secrets.yaml

apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: databases
type: Opaque
stringData:
  REDIS_PASSWORD: "EG0MtCsthwBc45VxCU6SFLD8jqixA69S0l19txGa"
