# Migration Job - Runs on app1 namespace
#
# This job runs the Laravel migration command on app1.
# It uses the laravel-app-config ConfigMap for environment variables.
#
# The job name uses generateName so each run creates a unique job.
# Old completed jobs are cleaned up automatically after 5 minutes (ttlSecondsAfterFinished).
#
# CI/CD usage:
#   kubectl create -f apps/app1/migration.yaml   (use create, not apply — generateName requires it)
#
# Manual usage:
#   kubectl create -f apps/app1/migration.yaml

# Delete the job with:
# kubectl delete job app1-migration -n apps

apiVersion: batch/v1
kind: Job
metadata:
  name: app1-migration
  namespace: app1
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      containers:
        - name: app1-migration
          image: hub.connoisseur-suite.co.uk/test/laravel-app:latest
          imagePullPolicy: Always
          command: ["php", "artisan", "migrate", "--force"]
          envFrom:
            - configMapRef:
                name: laravel-app-config
            - secretRef:
                name: app1-secrets
      imagePullSecrets:
        - name: regcred
      restartPolicy: Never
  backoffLimit: 0