# Secrets - Sensitive configuration values
#
# SWARM EQUIVALENT: This replaces your external Docker Swarm secrets.
# In Swarm, you create each secret separately:
#   docker secret create app_key ./secret-file
#   docker secret create db_password ./secret-file
#
# In K8s, you group ALL sensitive values into one Secret object.
# They get injected as environment variables into the container at runtime.
#
# KEY DIFFERENCES FROM SWARM:
#
# 1. In Swarm, secrets are mounted as FILES at /run/secrets/<secret_name>
#    Each secret is a separate file containing just the value.
#
# 2. In K8s, you have TWO options:
#    Option A: Inject as ENVIRONMENT VARIABLES (most common, what we use here)
#      - envFrom.secretRef loads ALL keys as env vars
#      - Or use env.valueFrom.secretKeyRef for individual keys
#
#    Option B: Mount as FILES at /run/secrets/ (identical to Swarm)
#      - Use volumeMounts + volumes with secret type
#
# 3. In Swarm, each secret is a separate object (docker secret create).
#    In K8s, you group related secrets into ONE Secret object with multiple keys.
#
# HOW SECRETS + CONFIGMAP WORK TOGETHER:
#   Your image already has a .env baked in with non-sensitive values.
#   Secrets OVERRIDE those values at runtime via environment variables.
#   ConfigMap also OVERRIDES values (like DB_HOST which changes in K8s).
#   Priority: Secret > ConfigMap > baked .env in image
#
# SECURITY NOTE:
#   - stringData values are auto-encoded to base64 when applied
#   - NEVER commit real secrets to git
#   - For production, look into External Secrets Operator or HashiCorp Vault
#
# Apply with: kubectl apply -f secrets.yaml
# kubectl apply -f apps/app1/secrets.yaml

apiVersion: v1
kind: Secret
metadata:
  name: app1-secrets
  namespace: apps
type: Opaque
stringData:
  # Laravel app key (used for encryption)
  APP_KEY: "base64:rft94tSbRGsFgoL44dO5QcymsluzFfXPlW5qbkhaaZI="

  # MariaDB Galera credentials
  # These MUST match what we set when installing the MariaDB Helm chart
  DB_PASSWORD: "secret"

  # MariaDB root password (for migrations, admin tasks)
  DB_ROOT_PASSWORD: "secret"

  # Redis password
  # Must match --set auth.password when installing Redis Helm chart
  REDIS_PASSWORD: "secret"

  # MongoDB credentials
  # Must match --set auth.rootPassword when installing MongoDB Helm chart
  MONGODB_USERNAME: "root"
  MONGODB_PASSWORD: "secret"
