services:
  widget:
    image: hub.connoisseur-suite.co.uk/production/fluent-widget:v1.0.24
    env_file:
      - /mnt/data/config/env/fluent-widget.env
    networks:
      - web2
    secrets:
      - fluent_mongodb_password
      - fluent_db_password
    healthcheck:
      test: ["CMD", "curl", "-f", "0.0.0.0:3000/healthcheck"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    deploy:
      replicas: 3
      update_config:
        parallelism: 0
        delay: 0s
      restart_policy: 
        condition: on-failure
      resources:
        limits:
          memory: 2G
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.fluent_widget.rule=Host(`fluent-widget.connoisseur-suite.com`)
        - traefik.http.routers.fluent_widget.entrypoints=websecure
        - traefik.http.routers.fluent_widget.tls=true
        - traefik.http.routers.fluent_widget.tls.certresolver=production
        - traefik.http.services.fluent_widget.loadbalancer.server.port=3000

networks:
  web2:
    external: true

secrets:
  fluent_db_password:
    external: true
  fluent_mongodb_password:
    external: true