services:
  mongodb:
    image: mongo:8.2.3
    networks:
      - web2
    volumes:
      - mongodb_data:/data/db
      - /mnt/data/mongo-backup:/backup
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo-rocks
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/fluent_mongodb_password
    secrets:
      - fluent_mongodb_password
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 30s
        failure_action: rollback
        monitor: 10s
        max_failure_ratio: 0.1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=false"

  mongo-express:
    image: mongo-express:1.0.2
    networks:
      - web2
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo-rocks
      ME_CONFIG_MONGODB_ADMINPASSWORD: d1q0sWuy4drErivI7USw
      ME_CONFIG_MONGODB_URL: mongodb://mongo-rocks:d1q0sWuy4drErivI7USw@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: ssr-admin
      ME_CONFIG_BASICAUTH_PASSWORD: 98_ujah£41+1334
    depends_on:
      - mongodb
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 30s
        failure_action: rollback
        monitor: 10s
        max_failure_ratio: 0.1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.mongo-express.rule=Host(`mongo.connoisseur-suite.com`)"
        - "traefik.http.routers.mongo-express.entrypoints=websecure"
        - "traefik.http.routers.mongo-express.tls=true"
        - "traefik.http.routers.mongo-express.tls.certresolver=production"
        - "traefik.http.services.mongo-express.loadbalancer.server.port=8081"

  mongodump:
    image: devasdf/mongodump:latest
    environment:
      - MONGO_USERNAME=mongo-rocks
      - MONGO_PASSWORD=d1q0sWuy4drErivI7USw
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - CRON_SCHEDULE=0 3 * * *
    volumes:
      - /mnt/data/mongo-backup:/backup
    depends_on:
      - mongodb
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 30s
        failure_action: rollback
        monitor: 10s
        max_failure_ratio: 0.1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=false"
    networks:
      - web2

networks:
  web2:
    external: true

volumes:
  mongodb_data:

secrets:
  fluent_mongodb_password:
    external: true
