services:
  impress:
    image: hub.connoisseur-suite.co.uk/production/impress:v1.3.48
    entrypoint: ["php", "artisan", "octane:start", "--host=0.0.0.0", "--port=9000", "--workers=5", "--server=swoole", "--max-requests=1000"]
    networks:
      - web2
    secrets:
      - impress_app_key
      - impress_db_password
      - impress_db_password_auth
    volumes:
      - /mnt/data/impress/data:/app/storage
    deploy:
      replicas: 1
      update_config:
        parallelism: 0
        delay: 0s
      restart_policy: 
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.http.routers.impress.rule=Host(`impress.connoisseur-suite.com`)
        - traefik.http.routers.impress.entrypoints=websecure
        - traefik.http.routers.impress.tls=true
        - traefik.http.routers.impress.tls.certresolver=production
        - traefik.http.services.impress.loadbalancer.server.port=9000
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 1.5G


networks:
  web2:
    external: true

secrets:
  impress_app_key:
    external: true
  impress_db_password:
    external: true
  impress_db_password_auth:
    external: true