services:
  timesheet:
    image: hub.connoisseur-suite.co.uk/production/timesheet:v1.0.3
    networks:
      - web2
    deploy:
      replicas: 1
      restart_policy: 
        condition: any
      resources:
        limits:
          memory: 1G
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.timesheet.rule=Host(`timesheet.connoisseur-suite.com`)
        - traefik.http.services.timesheet.loadbalancer.server.port=9000
        - traefik.http.routers.timesheet.entrypoints=websecure
        - traefik.http.routers.timesheet.tls=true
        - traefik.http.routers.timesheet.tls.certresolver=production

  reverb-timesheet:
    image: hub.connoisseur-suite.co.uk/production/timesheet:v1.0.3
    entrypoint: ["php", "artisan", "reverb:start", "--debug"]
    networks:
      - web2
    deploy:
      replicas: 1
      restart_policy: 
        condition: on-failure
      resources:
        limits:
          memory: 500M
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.reverb-timesheet.rule=Host(`reverb-timesheet.connoisseur-suite.com`)
        - traefik.http.services.reverb-timesheet.loadbalancer.server.port=8001
        - traefik.http.routers.reverb-timesheet.entrypoints=websecure
        - traefik.http.routers.reverb-timesheet.tls=true
        - traefik.http.routers.reverb-timesheet.tls.certresolver=production

networks:
  web2:
    external: true

