# mongo-express - MongoDB Web UI
#
# SWARM EQUIVALENT: Your deployments/mongo-stack/stack.yaml has this exact service:
#   services:
#     mongo-express:
#       image: mongo-express:1.0.2
#       environment:
#         ME_CONFIG_MONGODB_SERVER: mongodb
#         ME_CONFIG_MONGODB_ADMINUSERNAME: ssr-admin
#         ME_CONFIG_BASICAUTH_USERNAME: ssr-admin
#
# The K8s version is almost identical - just the hostname changes
# from "mongodb" (Swarm service name) to "mongodb" (K8s service in same namespace).
#
# Access: http://mongo-express.localhost (via Traefik Ingress)
# Login:  admin / secret
#
# Apply with: kubectl apply -f mongo-express.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  namespace: databases
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
        - name: mongo-express
          image: mongo-express:latest
          ports:
            - containerPort: 8081
          env:
            # MongoDB connection
            # Same namespace so short name works. Points to the primary.
            # Connect to MongoDB primary via headless service DNS
            # Format: <pod-name>.<headless-service>.<namespace>.svc
            - name: ME_CONFIG_MONGODB_URL
              value: "mongodb://root:secret@mongodb-0.mongodb-headless:27017/admin"

            # mongo-express login credentials (to access the UI itself)
            - name: ME_CONFIG_BASICAUTH_USERNAME
              value: "admin"
            - name: ME_CONFIG_BASICAUTH_PASSWORD
              value: "secret"
          resources:
            limits:
              memory: "256Mi"
            requests:
              memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express
  namespace: databases
spec:
  selector:
    app: mongo-express
  ports:
    - port: 8081
      targetPort: 8081
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mongo-express
  namespace: databases
spec:
  ingressClassName: traefik
  rules:
    - host: mongo.test
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mongo-express
                port:
                  number: 8081
