services:
  fast:
    image: hub.connoisseur-suite.co.uk/production/fast:v1.1.2
    volumes:
      - /mnt/data/fast/data:/app/storage
    networks:
      - web2
    secrets:
      - fast_app_key
      - fast_db_password
      - fast_db_password_auth
    deploy:
      replicas: 2
      update_config:
        parallelism: 0
        delay: 0s
        order: start-first
      restart_policy: 
        condition: on-failure
      resources:
        limits:
          memory: 1.5G
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.fast.rule=Host(`fast.connoisseur-suite.com`)
        - traefik.http.routers.fast.entrypoints=websecure
        - traefik.http.routers.fast.tls=true
        - traefik.http.routers.fast.tls.certresolver=production
        - traefik.http.services.fast.loadbalancer.server.port=9000

networks:
  web2:
    external: true

secrets:
  fast_app_key:
    external: true
  fast_db_password:
    external: true
  fast_db_password_auth:
    external: true