services:
  redis-gui:
    image: redis/redisinsight:latest
    networks:
      - web2
    deploy:
      replicas: 1
      restart_policy: 
        condition: on-failure
      resources:
        limits:
          memory: 1G
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.redis-gui.rule=Host(`redis.connoisseur-suite.com`)
        - traefik.http.services.redis-gui.loadbalancer.server.port=5540
        - traefik.http.routers.redis-gui.entrypoints=websecure
        - traefik.http.routers.redis-gui.tls=true
        - traefik.http.routers.redis-gui.tls.certresolver=production
        - "traefik.http.routers.redis-gui.middlewares=auth"
        - "traefik.http.middlewares.auth.basicauth.users=ssr-admin:$$2y$$05$$DZ1wvrVWmKJH3kT3eM7GQ.jBcF918sp7eje1uAqdXoK0uFMy7Ego2"

networks:
  web2:
    external: true

