services:
  eaat2:
    image: eaat2:latest
    volumes:
      - eaat2_data:/var/www/storage
    networks:
      - web2
    deploy:
      replicas: 6
      update_config:
        parallelism: 1
        delay: 30s
        failure_action: rollback
        monitor: 10s
        max_failure_ratio: 0.1
      restart_policy: 
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.eaat2.rule=Host(`eaat2.connoisseur-suite.com`)
        - traefik.http.routers.eaat2.entrypoints=websecure
        - traefik.http.routers.eaat2.tls=true
        - traefik.http.routers.eaat2.tls.certresolver=production
        - traefik.http.services.eaat2.loadbalancer.server.port=80
        
  eaat2-engine:
    image: eaat2-engine:latest
    networks:
      - web2
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 30s
        failure_action: rollback
        monitor: 10s
        max_failure_ratio: 0.1
      restart_policy: 
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.eaat2_engine.rule=Host(`eaat2-engine.connoisseur-suite.com`)
        - traefik.http.routers.eaat2_engine.entrypoints=websecure
        - traefik.http.routers.eaat2_engine.tls=true
        - traefik.http.routers.eaat2_engine.tls.certresolver=production
        - traefik.http.services.eaat2_engine.loadbalancer.server.port=80

  eaat2-engine-ff:
    image: eaat2-engine-ff:latest
    networks:
      - web2
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 30s
        failure_action: rollback
        monitor: 10s
        max_failure_ratio: 0.1
      restart_policy: 
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.eaat2_engine_ff.rule=Host(`eaat2-engine-ff.connoisseur-suite.com`)
        - traefik.http.routers.eaat2_engine_ff.entrypoints=websecure
        - traefik.http.routers.eaat2_engine_ff.tls=true
        - traefik.http.routers.eaat2_engine_ff.tls.certresolver=production
        - traefik.http.services.eaat2_engine_ff.loadbalancer.server.port=80

networks:
  web2:
    external: true

volumes:
  eaat2_data: