services:
  eaat2:
    image: eaat2:latest
    volumes:
      - eaat2_data:/var/www/storage
    networks:
      - web
    deploy:
      replicas: 1
      restart_policy: 
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.http.routers.eaat2.rule=Host(`eaat2.local`)
        - traefik.http.routers.eaat2.entrypoints=websecure
        - traefik.http.routers.eaat2.tls=true
        - traefik.http.services.eaat2.loadbalancer.server.port=80
  eaat2-engine:
    image: eaat2-engine:latest
    networks:
      - web
    deploy:
      replicas: 1
      restart_policy: 
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.http.routers.eaat2_engine.rule=Host(`eaat2-engine.local`)
        - traefik.http.routers.eaat2_engine.entrypoints=websecure
        - traefik.http.routers.eaat2_engine.tls=true
        - traefik.http.services.eaat2_engine.loadbalancer.server.port=80
  
  eaat2-engine-ff:
    image: eaat2-engine-ff:latest
    networks:
      - web
    deploy:
      replicas: 1
      restart_policy: 
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.http.routers.eaat2_engine_ff.rule=Host(`eaat2-engine-ff.local`)
        - traefik.http.routers.eaat2_engine_ff.entrypoints=websecure
        - traefik.http.routers.eaat2_engine_ff.tls=true
        - traefik.http.services.eaat2_engine_ff.loadbalancer.server.port=80

networks:
  web:
    external: true

volumes:
  eaat2_data: