services:
  engine:
    image: hub.connoisseur-suite.co.uk/production/act-engine:v1.0.1
    networks:
      - web2
    deploy:
      replicas: 6
      restart_policy: 
        condition: on-failure
      resources:
        limits:
          memory: 500M
      labels:
        - traefik.enable=true
        - traefik.http.routers.act_engine.rule=Host(`act-engine.connoisseur-suite.com`)
        - traefik.http.routers.act_engine.entrypoints=websecure
        - traefik.http.routers.act_engine.tls=true
        - traefik.http.routers.act_engine.tls.certresolver=production
        - traefik.http.services.act_engine.loadbalancer.server.port=80
    

networks:
  web2:
    external: true