version: '3.8'

services:
  registry:
    image: registry:2
    command: /etc/docker/registry/config.yml
    environment:
      - REGISTRY_AUTH=htpasswd
      - REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm
      - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
      - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/data
      - "REGISTRY_HTTP_HEADERS_Access-Control-Allow-Origin=['https://registry.connoisseur-suite.co.uk']"
      - "REGISTRY_HTTP_HEADERS_Access-Control-Allow-Methods=['HEAD,GET,OPTIONS,DELETE']"
      - "REGISTRY_HTTP_HEADERS_Access-Control-Allow-Credentials=['true']"
      - "REGISTRY_HTTP_HEADERS_Access-Control-Allow-Headers=['Authorization,Accept,Cache-Control']"
      - "REGISTRY_HTTP_HEADERS_Access-Control-Expose-Headers=['Docker-Content-Digest']"
      - "REGISTRY_STORAGE_DELETE_ENABLED=true"
    volumes:
      - registry_data:/data
      - ./auth:/auth
    networks:
      - web
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.registry.rule=Host(`hub.connoisseur-suite.co.uk`)"
        - "traefik.http.routers.registry.entrypoints=websecure"
        - "traefik.http.routers.registry.tls=true"
        - "traefik.http.routers.registry.tls.certresolver=production"
        - "traefik.http.services.registry.loadbalancer.server.port=5000"
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure

  registry-ui:
    image: joxit/docker-registry-ui:main
    environment:
      - SINGLE_REGISTRY=true
      - REGISTRY_TITLE=Docker Registry UI
      - DELETE_IMAGES=true
      - SHOW_CONTENT_DIGEST=true
      - NGINX_PROXY_PASS_URL=http://registry:5000
      - SHOW_CATALOG_NB_TAGS=true
      - CATALOG_MIN_BRANCHES=1
      - CATALOG_MAX_BRANCHES=1
      - TAGLIST_PAGE_SIZE=100
      - REGISTRY_SECURED=false
      - CATALOG_ELEMENTS_LIMIT=1000
      - PULL_URL=https://hub.connoisseur-suite.co.uk
    networks:
      - web
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.registry-ui.rule=Host(`registry.connoisseur-suite.co.uk`)"
        - "traefik.http.routers.registry-ui.entrypoints=websecure"
        - "traefik.http.routers.registry-ui.tls=true"
        - "traefik.http.routers.registry-ui.tls.certresolver=production"
        - "traefik.http.services.registry-ui.loadbalancer.server.port=80"
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure

volumes:
  registry_data:
    driver: local

networks:
  web:
    external: true
