services:
  csuitecouk-wordpress:
    image: wordpress:php8.3-apache
    env_file:
      - ${HOME}/config/env/csuite-co-uk2.env
    volumes:
      - /mnt/data/csuite-co-uk/public_html:/var/www/html
      - ./php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - web2
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 30s
        failure_action: rollback
        monitor: 10s
        max_failure_ratio: 0.1
      restart_policy: 
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.csuitecouk.rule=Host(`connoisseur-suite.co.uk`)
        - traefik.http.routers.csuitecouk.entrypoints=websecure
        - traefik.http.routers.csuitecouk.tls=true
        - traefik.http.routers.csuitecouk.tls.certresolver=production
        - traefik.http.services.csuitecouk.loadbalancer.server.port=80

networks:
  web2:
    external: true