services:
  timesheet:
    image: hub.connoisseur-suite.co.uk/production/timesheet:v1.0.3
    networks:
      - web2
    deploy:
      replicas: 1
      restart_policy: 
        condition: any
      resources:
        limits:
          memory: 1G
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.timesheet.rule=Host(`timesheet.connoisseur-suite.com`)
        - traefik.http.services.timesheet.loadbalancer.server.port=9000
        - traefik.http.routers.timesheet.entrypoints=websecure
        - traefik.http.routers.timesheet.tls=true
        - traefik.http.routers.timesheet.tls.certresolver=production

networks:
  web2:
    external: true

