services:
  express:
    image: hub.connoisseur-suite.co.uk/staging/express:v2.0.0
    volumes:
      - caddy_express_data:/data
      - caddy_express_config:/config
      - express_data:/app/storage
      - express_assets:/app/public/gallery
    networks:
      - web
    secrets:
      - express_db_password
      - express_db_password_auth
      - express_app_key
    deploy:
      replicas: 1
      restart_policy: 
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.http.routers.express.rule=Host(`express.connoisseur-suite.co.uk`)
        - traefik.http.routers.express.entrypoints=websecure
        - traefik.http.routers.express.tls=true
        - traefik.http.routers.express.tls.certresolver=production
        - traefik.http.services.express.loadbalancer.server.port=80
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost"]
    #   interval: 1m30s
    #   timeout: 30s
    #   retries: 5
    #   start_period: 30s
    

  express-engine:
    image: hub.connoisseur-suite.co.uk/staging/express-engine:v1.1.4
    networks:
      - web
    deploy:
      replicas: 1
      restart_policy: 
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.http.routers.express_engine.rule=Host(`express-engine.connoisseur-suite.co.uk`)
        - traefik.http.routers.express_engine.entrypoints=websecure
        - traefik.http.routers.express_engine.tls=true
        - traefik.http.routers.express_engine.tls.certresolver=production
        - traefik.http.services.express_engine.loadbalancer.server.port=80
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:9000"]
    #   interval: 1m30s
    #   timeout: 30s
    #   retries: 5
    #   start_period: 30s
    

networks:
  web:
    external: true

volumes:
  caddy_express_data:
  caddy_express_config:
  express_data:
  express_assets:

secrets:
  express_db_password:
    external: true
  express_db_password_auth:
    external: true
  express_app_key:
    external: true