services:
   qdrant:
    image: qdrant/qdrant:latest
    restart: unless-stopped
    networks:
      - web
    environment:
      - QDRANT__GRPC__ENABLED=true
      - QDRANT__HTTP__ENABLED=true
      - QDRANT__HOST=0.0.0.0
    volumes:
      - qdrant_data:/qdrant/storage
    deploy:
      resources:
        limits:
          memory: 1.5G
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=false

networks:
  web:
    external: true

volumes:
  qdrant_data:
