services:
  imprint-server:
    image: hub.connoisseur-suite.co.uk/production/imprint-server:v1.0.0
    env_file:
      - /mnt/data/config/env/imprint-server.env
    volumes:
      - /mnt/data/imprint-stack/imprint-server:/var/www/public
    networks:
      - web2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8080/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 30s
        failure_action: rollback
        monitor: 10s
        max_failure_ratio: 0.1
      restart_policy: 
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.http.routers.imprint_server.rule=Host(`imprint-server.connoisseur-suite.com`)
        - traefik.http.routers.imprint_server.entrypoints=websecure
        - traefik.http.routers.imprint_server.tls=true
        - traefik.http.routers.imprint_server.tls.certresolver=production
        - traefik.http.services.imprint_server.loadbalancer.server.port=8080

  imprint-ide:
    image: hub.connoisseur-suite.co.uk/production/imprint-ide:v1.0.0
    networks:
      - web2
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 30s
        failure_action: rollback
        monitor: 10s
        max_failure_ratio: 0.1
      restart_policy: 
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.http.routers.imprint_ide.rule=Host(`imprint-ide.connoisseur-suite.com`)
        - traefik.http.routers.imprint_ide.entrypoints=websecure
        - traefik.http.routers.imprint_ide.tls=true
        - traefik.http.routers.imprint_ide.tls.certresolver=production
        - traefik.http.services.imprint_ide.loadbalancer.server.port=80

  imprint-engine:
    image: hub.connoisseur-suite.co.uk/production/imprint-engine:v1.0.0
    networks:
      - web2
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 30s
        failure_action: rollback
        monitor: 10s
        max_failure_ratio: 0.1
      restart_policy: 
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.http.routers.imprint_engine.rule=Host(`imprint-engine.connoisseur-suite.com`)
        - traefik.http.routers.imprint_engine.entrypoints=websecure
        - traefik.http.routers.imprint_engine.tls=true
        - traefik.http.routers.imprint_engine.tls.certresolver=production
        - traefik.http.services.imprint_engine.loadbalancer.server.port=80

networks:
  web2:
    external: true