services:
  imprint-server:
    image: hub.connoisseur-suite.co.uk/staging/imprint-server:v1.0.0
    env_file:
      - ${HOME}/config/env/imprint-server.env
    volumes:
      - imprint_data:/var/www/public
    networks:
      - web
    deploy:
      replicas: 1
      restart_policy: 
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.http.routers.imprint_server.rule=Host(`imprint-server.connoisseur-suite.co.uk`)
        - traefik.http.routers.imprint_server.entrypoints=websecure
        - traefik.http.routers.imprint_server.tls=true
        - traefik.http.routers.imprint_server.tls.certresolver=production
        - traefik.http.services.imprint_server.loadbalancer.server.port=8080

  imprint-ide:
    image: hub.connoisseur-suite.co.uk/staging/imprint-ide:v1.0.0
    networks:
      - web
    deploy:
      replicas: 1
      restart_policy: 
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.http.routers.imprint_ide.rule=Host(`imprint-ide.connoisseur-suite.co.uk`)
        - traefik.http.routers.imprint_ide.entrypoints=websecure
        - traefik.http.routers.imprint_ide.tls=true
        - traefik.http.routers.imprint_ide.tls.certresolver=production
        - traefik.http.services.imprint_ide.loadbalancer.server.port=80

  imprint-engine:
    image: hub.connoisseur-suite.co.uk/staging/imprint-engine:v1.0.0
    networks:
      - web
    deploy:
      replicas: 1
      restart_policy: 
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.http.routers.imprint_engine.rule=Host(`imprint-engine.connoisseur-suite.co.uk`)
        - traefik.http.routers.imprint_engine.entrypoints=websecure
        - traefik.http.routers.imprint_engine.tls=true
        - traefik.http.routers.imprint_engine.tls.certresolver=production
        - traefik.http.services.imprint_engine.loadbalancer.server.port=80

networks:
  web:
    external: true

volumes:
  imprint_data: