services:
  engine:
    image: hub.connoisseur-suite.co.uk/staging/express-engine:v1.6.0
    networks:
      - web
    deploy:
      replicas: 1
      restart_policy: 
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.http.routers.express_engine.rule=Host(`express-engine.connoisseur-suite.co.uk`)
        - traefik.http.routers.express_engine.entrypoints=websecure
        - traefik.http.routers.express_engine.tls=true
        - traefik.http.routers.express_engine.tls.certresolver=production
        - traefik.http.services.express_engine.loadbalancer.server.port=80
    
networks:
  web:
    external: true