services:
  express:
    image: hub.connoisseur-suite.co.uk/staging/express:v3.0.10
    volumes:
      - /mnt/nfs/shared/express/data:/app/storage
      - /mnt/nfs/shared/express/assets:/app/public/gallery
      - /mnt/nfs/shared/fluent/ide/app/public/galleries:/app/storage/app/public/galleries
    networks:
      - web
    secrets:
      - express_db_password
      - express_db_password_auth
      - express_app_key
      - express_mongodb_password
      - express_pusher_app_secret
    deploy:
      replicas: 2
      restart_policy: 
        condition: on-failure
      resources:
        limits:
          memory: 2GB
      labels:
        - traefik.enable=true
        - traefik.http.routers.express.rule=Host(`express.connoisseur-suite.co.uk`)
        - traefik.http.routers.express.entrypoints=websecure
        - traefik.http.routers.express.tls=true
        - traefik.http.routers.express.tls.certresolver=production
        - traefik.http.services.express.loadbalancer.server.port=9000
      placement:
        constraints:
          - node.role == worker


networks:
  web:
    external: true

secrets:
  express_db_password:
    external: true
  express_db_password_auth:
    external: true
  express_app_key:
    external: true
  express_mongodb_password:
    external: true
  express_pusher_app_secret:
    external: true