services:
  documentation:
    image: hub.connoisseur-suite.co.uk/production/documentation:v1.0.0
    volumes:
      - /mnt/data/docs/data:/app/storage
    networks:
      - web2
    deploy:
      replicas: 1
      update_config:
        parallelism: 0
        delay: 0s
        order: start-first
      restart_policy: 
        condition: on-failure
      resources:
        limits:
          memory: 1.5G
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.documentation.rule=Host(`docs.connoisseur-suite.com`)
        - traefik.http.routers.documentation.entrypoints=websecure
        - traefik.http.routers.documentation.tls=true
        - traefik.http.routers.documentation.tls.certresolver=production
        - traefik.http.services.documentation.loadbalancer.server.port=80

networks:
  web2:
    external: true