services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    devices:
      - "/dev/kmsg"
    networks:
      - web
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
      labels:
        - "traefik.enable=false"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    privileged: true

  prometheus:
    image: prom/prometheus:v2.49.1
    networks:
      - web
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=15d'
      - '--web.enable-lifecycle'
      - '--storage.tsdb.wal-compression'
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
      labels:
        - "traefik.enable=false"

  grafana:
    image: grafana/grafana:10.2.4
    networks:
      - web
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD_FILE=/run/secrets/grafana_admin_password
      - GF_INSTALL_PLUGINS=grafana-piechart-panel,grafana-clock-panel
    secrets:
      - grafana_admin_password
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.grafana.rule=Host(`grafana.connoisseur-suite.co.uk`)"
        - "traefik.http.routers.grafana.entrypoints=websecure"
        - "traefik.http.services.grafana.loadbalancer.server.port=3000"
        - "traefik.http.routers.grafana.tls=true"
        - "traefik.http.routers.grafana.tls.certresolver=production"
        # echo "3lfraWrljI2e" | docker secret create grafana_admin_password -

  node-exporter:
    image: prom/node-exporter:v1.7.0
    networks:
      - web
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
      labels:
        - "traefik.enable=false"

networks:
  web:
    external: true

volumes:
  prometheus_data:
  grafana_data:

secrets:
  grafana_admin_password:
    external: true